### ISSUE TITLE
DecodedInstruction is very slow; it's using hashtables

### ISSUE THREAD

**Issue by vbmacher** [emustudio/edigen#29]
See https://github.com/vbmacher/emuStudio/issues/141

**Comment by vbmacher** [comment]
Ok, after using TreeMap, it helped. However, the decoding algorithm in generated decoder is still very slow. Now the bottleneck is `DecoderImpl.read()`. Decoding a single instruction in Z80 CPU takes 202ms (measured usin VisualVM). It's unbelievable slow :) 

I see there are two/three problems with performance. At first there's lack of using well known information about how many bytes will be read for each instruction. We know that for each instruction before start of decoding it, thus there can be performed read of all required bytes right away. This way many unnecessary method calls and for loops can be avoided (possibly).

Second thing is, that the switch-like approach is performance killer. Processor jumps like crazy and tests whether the value is in each of the cases one-by-one. If there are many branches, I would not be able to look at it without crying (and there are...:'( ). Much better approach will be using tables. There can be many tables generated, in which value items shall be values used as parameters for calling `instruction.add()`.

Third problem is probably caused by non-cached copying of bytes to the instruction image. All bytes which are constant don't have to be copied, they can be referenced.

**Comment by sulir** [comment]
Thank you for the feedback.

I think we do not know how many bytes to read before starting decoding an instruction. Often some instructions have one bytes, some two, some four, etc. Only after reading the first byte, we can know whether to read more bytes or not. Probably we could try to read some fixed number of bytes and cache them, if it would help.

Regarding the generated switch-case code, this is the core of the whole logic of Edigen. Generating code in another style would require a complete rewrite of the system. I thought that the JVM is intelligent enough to optimize the switch-case statements - to choose between tables and lookups to obtain the best time-memory compromise (see, e.g., http://stackoverflow.com/questions/10287700/difference-between-jvms-lookupswitch-and-tableswitch).

Anyway, this requires some time to examine and try remedies, so I will probably look at it no sooner than in the summer.

**Comment by vbmacher** [comment]
Thanks for the reply!

Well, after reading your first paragraph, I don't know why I thought that we know all bytes in the beginning. We definitely know it for some CPUs, like SSEM, where each instruction is always 4 bytes long. But in case of Z80, it varies from 1 - 4 bytes. Also, there might be some computers in the future in which byte won't be the base unit so I guess the only improvement here might be to "select" appropriate algorithm when detected it's possible.. I guess this is the lowest priority from the three problems I've described.

Secondly, I didn't know about the JVM "intelligence" regarding automatic table generations. According to the SO answer, it seems the keys in the switch must be "compact enough" to be table-ized. I can't say right now how many holes there are in case of Z80 instructions, but I know there are some. Also, I don't know if the (multitude of) nested switch statements didn't prevent generation of tables, I haven't investigated it. Maybe if it was possible to "force" JVM to tableize everything, it might help? I think I don't really care about the memory consumption so far.

Finally, I definitely understand that it's not a simple task, and if implemented, it will consume a lot of time, and many rework. You are ofcourse free to do it or not to do it, it is up to you. I would rather be if there will be more people contributing; but I heard that the interest from students is quite low...

**Comment by sulir** [comment]
I was not able to reproduce the slowdown you are describing. Decoding each instruction in 200 ms would make the GUI unresponsive - and I did not observe any freezes.

I also tried profiling with VisualVM, but the decoder methods were not even displayed in the list of hot-spots.

Anyway, I wrote a simple benchmark:
```
int count = 10_000;
long startTime = System.nanoTime();
for (int i = 0; i < count; i++) {
    decoder.decode(0);
}
long endTime = System.nanoTime();
System.out.println((endTime - startTime) / (double) count);
```
The average time for decoding one instruction (`ld a, 1` on Z80) was around 1000 ns, which is 1μs (microsecond).

When I load a new program into memory, compiling some of the first few instructions can take tens (very occasionally hundreds) of microseconds. Subsequent decodings are much quicker.

All the times I mentioned are nowhere near the 200 ms you mentioned. How exactly did you achieve and measure such slowness?

**Comment by vbmacher** [comment]
I had measured imlementations using TreeMaps or HashMaps and HashMap is clear winner regarding the performance. So I have returned them back. See https://github.com/emustudio/emuLib/issues/38 for more information. For now, I think this might be closed.
