### ISSUE TITLE
Support either multiple root rules or "else" construct if root rule fails

### ISSUE THREAD

**Issue by vbmacher** [emustudio/edigen#34]
Sometimes it is handy to recover from `InvalidInstructionException` while decoding by trying another rule - e.g. if the bytes do not represent an instruction, they represent data (and we want to show it in dissasembler).

### Proposal 1
Currently, the first rule in the file is the only root rule. If this rule fails, there's no possibility to try other path. One solution would be to have multiple root rules (either explicitly specified - or taken as the first rules appearing in all lines in the dissasembler part) and try apply from the first to the last. For example:

```
...
%%

"%s %d" = instruction line(shift_left, shift_left, shift_left, bit_reverse, absolute) ignore8 ignore16;
"%s" = instruction ignore8 ignore16;
"%s %d" = number num(bit_reverse);
```

In this code the rules `instruction, number` are root rules and will be tried in this order.

### Proposal 2
Another solution would be being able to capture the unmatched input in the only root rule, for example as:

```
instruction =  "JMP": line(5)     ignore8(8) 000 ignore16(16) |
               "JPR": line(5)     ignore8(8) 100 ignore16(16) |
               ... |
               <otherwise> "DATA": data(32)
```

We can debate how the `<otherwise>` part should be named. This part would be optional.

Why the `<otherwise>` is this actually needed is because of possible ambiguities with instructions (e.g. pattern `000...0` is ambiguous). I don't really want to explicitly specify all possible values except the ambiguous ones - this is what I expect from the `<otherwise>` part.

@sulir what do you think about it?

**Comment by vbmacher** [comment]
Advantage of Proposal 1 gives multiple chances to recover, since there can be multiple root rules. The proposal 2 has just one last chance to recover, because there's just one `<otherwise>`. It also should be noted that in Proposal 2 only the root rule can have `<otherwise>` part, not child rules.

**Comment by sulir** [comment]
I am not convinced this feature is necessary. If the aim is to recover from the situation when the instruction is not successfully decoded (e.g., to show data), then the Java source code of the disassembler can handle this exception and show the data.

Proposal 1 will break existing CPUs - e.g., Z80:
```
instruction = "nop": ... | 0xDD ddINSTR;
%%
"..." = instruction ...;
"..." = ddINSTR ...;
```
Then `ddINSTR` would be considered a possible root value, which could result in incorrect decoding.

Proposal 2 is acceptable (if the feature is really necessary).

**Comment by vbmacher** [comment]
Regarding the feature - my argument of it's "necessity" is as follows. The whole point of this project is to simplify development of decoder and disassembler, right? If the only solution of this situation (which might be very common) is to prepare custom decoder template, it is unfortutnate in my opinion. I think we should allow handling customizations or situations like this in the spec file, so Edigen can handle it and not programmer. We should be aiming at improving edigen automation to help developer free himself/herself from manual work and hacks.

Regarding Proposal 1 - I didn't mean "all rules" should be root ones, only those which are explicitly marked. For example:

```
root instruction, data

instruction = ...
data = ...
``` 

Each rule can handle only part of the input - only rule has its mask. If there are unhandled bits in the mask of the `instruction` rule, the bits can be handled with `data` rule. The `data` rule might or might not handle the bits - if it handles them, decoder will succeed. If not, decoder will throw runtime exception (current state).

**Comment by vbmacher** [comment]
If I look at it now, maybe I like proposal 1 even more than proposal 2. It is more general and the grammar change looks nicer (even helps to clarify which rule is root) than in proposal 2.

**Comment by sulir** [comment]
OK, Proposal 1 looks good when using the `root` keyword as described.

**Comment by vbmacher** [comment]
When accessing root rules, we can run in a situation as follows:

```
root instruction, data;

instruction, data = line(5) 111;
```

Which in fact doesn't make any sense. Due the possibility of having multiple names of the rule we might be trying one rule multiple times, or we must implement a check if various names don't point to the same rule. It smells of needless complexity, I mean the whole feature of allowing multiple names of a rule. Therefore I've submitted ticket #47

**Comment by vbmacher** [comment]
The feature is useful, so Im keeping it. There should instead exist a deduplication mechanism
