### ISSUE TITLE
Remove RuleNameSet - allow only one name of a rule

### ISSUE THREAD

**Issue by vbmacher** [emustudio/edigen#47]
Currently, a rule can have multiple names, e.g.:

```
instruction, data = line(5) 111;
```

However I don't really see a point why. I think one rule should have unique name and it should be an identifier of the rule. The current situation complicates identifying rule in code, e.g.:

```java
    /**
     * Returns a human-readable label of this rule - a name or a list of names
     * separated by commas.
     * @return the label
     */
    public String getLabel() {
        Iterator<String> nameIterator = names.iterator();
        StringBuilder result = new StringBuilder();
        
        while (nameIterator.hasNext()) {
            result.append(nameIterator.next());
            
            if (nameIterator.hasNext())
                result.append(", ");
        }
        
        return result.toString();
    }
```

In my opinion this is unnecessary. @sulir do you have some use cases why this feature might be useful? Thanks!

**Comment by sulir** [comment]
A potential use case is directly in the README:
```
...
src_reg, dst_reg =
    "X": 00 |
    "Y": 01;
%%
"%s %s, %s" = instruction dst_reg src_reg;
```

But it was only an abstract idea. If this feature is not used in any real plugin, you can safely remove it.

**Comment by vbmacher** [comment]
@sulir is the order of the rule names in the disassembler part significant? I mean, if we have:

```
instruction = "omg": 101 src_reg dst_reg
src_reg, dst_reg =
  "X": 00 |
  "Y": 01;

%%
"%s %s, %s" = instruction dst_reg src_reg
```

I expect that `src_reg` will be correctly substituted by first two bits in the binary image but shown as the last `%s` in the format as specified, so I can reorder the same bit appearance in the disassembler part. If it is like that, then this feature is pretty useful and I'll keep it.

**Comment by sulir** [comment]
Yes, the order in the disassembler should be preserved.

**Comment by vbmacher** [comment]
Thanks, so Im keeping the feature
